<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LauncherGo.ServerMapHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LauncherGo.Domains\LauncherGo.Domains.csproj" />
    <Content Include="WebRoot\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
