<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LauncherGo.GatewayHost</AssemblyName>
    <AppHostDotNetSearch Condition="'$(SelfContained)' != 'true'">Global</AppHostDotNetSearch>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LauncherGo.Services\LauncherGo.Services.csproj" />
  </ItemGroup>
</Project>
