using ServerMap.Util;

namespace ServerMap.Render;

public static class TileColorStamp
{
    // Bump only when the basic rendering algorithm changes, not on every build.
    private const string Format = "client-colors-5:";
    public static bool IsCurrent(string tilePath, string colorVersion)
    {
        if (colorVersion == "fallback" || !File.Exists(tilePath)) return false;
        try { return File.ReadAllText(tilePath + ".colors") == Format + colorVersion; }
        catch (IOException) { return false; }
    }
    public static void Invalidate(string tilePath)
    {
        var stampPath = tilePath + ".colors";
        try
        {
            // File.Delete normally treats a missing file as a no-op, but it
            // throws DirectoryNotFoundException when the parent tile folder
            // has not been created yet. That is normal for a newly discovered
            // region and must not fail the render job.
            if (File.Exists(stampPath)) File.Delete(stampPath);
        }
        catch (DirectoryNotFoundException) { }
        catch (FileNotFoundException) { }
    }
    public static void Complete(string tilePath, string colorVersion)
    {
        // A render can finish while a new save is creating its tile tree (or
        // while the old tree is being removed). Recreate the parent directory
        // here so the sidecar stamp cannot fail with DirectoryNotFoundException.
        var directory = Path.GetDirectoryName(tilePath);
        if (string.IsNullOrWhiteSpace(directory)) return;
        try
        {
            Directory.CreateDirectory(directory);
            AtomicFile.Replace(tilePath + ".colors", temp => File.WriteAllText(temp, Format + colorVersion));
        }
        catch (DirectoryNotFoundException)
        {
            // Save/profile switches may remove the tree between the directory
            // check and the atomic move. The PNG remains valid; its stamp can
            // be regenerated by the next render request.
        }
    }
}
