using System.Collections.Concurrent;
using System.IO.Compression;
using System.Text;
using ServerMap.Render;
using Vintagestory.API.Common;
using Vintagestory.API.Config;
using Vintagestory.API.Server;

namespace ServerMap.Network;

/// <summary>Reassembles and validates the colormap generated by a client.</summary>
public sealed class ClientColormapReceiver : IDisposable
{
    private const int MaxChunks = 1024;
    private const int MaxChunkBytes = 65536;
    private const int MaxCompressedBytes = 32 * 1024 * 1024;
    private const int MaxJsonBytes = 128 * 1024 * 1024;
    private const int TransferTimeoutMs = 60000;

    private readonly ICoreServerAPI api;
    private readonly MapPalette materials;
    private readonly Action colormapApplied;
    private readonly string colormapDirectory;
    private readonly ConcurrentDictionary<string, Transfer> transfers = new(StringComparer.Ordinal);
    private readonly long cleanupTaskId;

    public ClientColormapReceiver(ICoreServerAPI api, MapPalette materials, Action colormapApplied, string colormapDirectory)
    {
        this.api = api;
        this.materials = materials;
        this.colormapApplied = colormapApplied;
        this.colormapDirectory = colormapDirectory;
        cleanupTaskId = api.Event.RegisterGameTickListener(_ => Cleanup(), 30000);
    }

    public void Receive(IServerPlayer player, ClientColormapChunkPacket packet)
    {
        if (!player.HasPrivilege(Privilege.root))
        {
            api.Logger.Warning("ServerMap rejected colormap from non-root player {0}.", player.PlayerName);
            return;
        }

        if (packet.ProtocolVersion != 2
            || string.IsNullOrWhiteSpace(packet.TransferId) || packet.TransferId.Length > 80
            || packet.TotalChunks is <= 0 or > MaxChunks || packet.ChunkIndex < 0
            || packet.ChunkIndex >= packet.TotalChunks || packet.Data is not { Length: > 0 and <= MaxChunkBytes }
            || packet.Month is < 1 or > 12)
        {
            api.Logger.Warning("ServerMap rejected invalid colormap chunk from {0}.", player.PlayerName);
            return;
        }

        var key = player.PlayerUID + ":" + packet.TransferId;
        var transfer = transfers.GetOrAdd(key, _ => new Transfer(player.PlayerUID, player.PlayerName, packet.TotalChunks, packet.Month));
        lock (transfer.Sync)
        {
            if (transfer.TotalChunks != packet.TotalChunks || transfer.Month != packet.Month || transfer.Completed)
            {
                transfers.TryRemove(key, out _);
                return;
            }

            if (transfer.Parts[packet.ChunkIndex] == null)
            {
                transfer.Parts[packet.ChunkIndex] = packet.Data;
                transfer.Received++;
                transfer.Bytes += packet.Data.Length;
            }

            if (transfer.Bytes > MaxCompressedBytes)
            {
                transfers.TryRemove(key, out _);
                return;
            }

            if (transfer.Received != transfer.TotalChunks) return;
            transfer.Completed = true;
        }

        transfers.TryRemove(key, out _);
        Complete(player, transfer);
    }

    private void Complete(IServerPlayer player, Transfer transfer)
    {
        try
        {
            var compressed = new byte[transfer.Bytes];
            var offset = 0;
            foreach (var part in transfer.Parts)
            {
                if (part == null) throw new InvalidDataException("Missing colormap chunk.");
                Buffer.BlockCopy(part, 0, compressed, offset, part.Length);
                offset += part.Length;
            }

            using var input = new MemoryStream(compressed, writable: false);
            using var gzip = new GZipStream(input, CompressionMode.Decompress, leaveOpen: false);
            using var output = new MemoryStream();
            var buffer = new byte[81920];
            int read;
            while ((read = gzip.Read(buffer, 0, buffer.Length)) > 0)
            {
                if (output.Length + read > MaxJsonBytes) throw new InvalidDataException("Colormap JSON is too large.");
                output.Write(buffer, 0, read);
            }

            var json = Encoding.UTF8.GetString(output.GetBuffer(), 0, checked((int)output.Length));
            if (!materials.ApplyClientColormap(json, transfer.Month, out var resolved))
                throw new InvalidDataException("Colormap did not contain any valid 30-colour block entries.");
            MapPalette.SaveClientColormap(colormapDirectory, json, transfer.Month);

            api.Logger.Notification("ServerMap received client colormap from {0}: month {1}, {2} blocks.", player.PlayerName, transfer.Month, resolved);
            api.Event.EnqueueMainThreadTask(() =>
            {
                colormapApplied();
                player.SendMessage(GlobalConstants.CurrentChatGroup, $"ServerMap client colormap loaded ({resolved} blocks, month {transfer.Month}).", EnumChatType.CommandSuccess);
            }, "servermap-colormap-applied");
        }
        catch (Exception ex)
        {
            api.Logger.Warning("ServerMap failed to process client colormap from {0}: {1}", player.PlayerName, ex.Message);
        }
    }

    private void Cleanup()
    {
        var now = Environment.TickCount64;
        foreach (var pair in transfers)
        {
            if (now - pair.Value.StartedAt <= TransferTimeoutMs) continue;
            transfers.TryRemove(pair.Key, out _);
        }
    }

    public void Dispose()
    {
        api.Event.UnregisterGameTickListener(cleanupTaskId);
        transfers.Clear();
    }

    private sealed class Transfer
    {
        public readonly object Sync = new();
        public readonly string PlayerUid;
        public readonly string PlayerName;
        public readonly int TotalChunks;
        public readonly int Month;
        public readonly byte[][] Parts;
        public readonly long StartedAt = Environment.TickCount64;
        public int Received;
        public int Bytes;
        public bool Completed;

        public Transfer(string playerUid, string playerName, int totalChunks, int month)
        {
            PlayerUid = playerUid;
            PlayerName = playerName;
            TotalChunks = totalChunks;
            Month = month;
            Parts = new byte[totalChunks][];
        }
    }
}
